version: '3'
services:
  nginx:
    build: 
     context: ./nginx
     dockerfile: Dockerfile
    network_mode: host
    depends_on:
     - chatui
  mongodb:
   image: mongo:latest
   container_name: mongodb
   network_mode: host
  chatui:
   build: 
     context: ./chat-ui
     dockerfile: Dockerfile
   container_name: chatui
   depends_on:
     - mongodb
   network_mode: host